extend = "./pyproject.toml"

target-version = "py39"

indent-width = 4
line-length = 120

output-format = "pylint"
respect-gitignore = true

exclude = [
    "**/run.py",
]

[lint]
dummy-variable-rgx = "^(_|ignored|unused|args|kwargs)$"
preview = true
future-annotations = true
select = ["ALL"]
ignore = [
    "ANN", # flake8-annotations
    "FBT", # flake8-boolean-trap
    "CPY", # flake8-copyright
    "EM", # flake8-errmsg
    "TC001", # typing-only-first-party-import
    "TC002", # typing-only-third-party-import
    "TC003", # typing-only-standard-library-import
    "TD001", # invalid-todo-tag
    "TD002", # missing-todo-author
    "TD003", # missing-todo-link
    "COM812", # missing-trailing-comma
    "FIX002", # line-contains-todo
    "LOG015", # root-logger-call
    "DOC", # pydoclint
    "D", # pydocstyle
    "PLR6104", # non-augmented-assignment
    "PLR2004", # magic-value-comparison
    "PLR6301", # no-self-use
    "TRY003", # raise-vanilla-args
    "TRY201", # verbose-raise
    "TRY301", # raise-within-try
    "PLR0904", # too-many-public-methods
    "UP006", # non-pep585-annotation
    "UP035", # deprecated-import
]

[lint.per-file-ignores]
"__init__.py" = [
    "F401", # unused-import
]
"tests/**" = [
    "S101", # assert
    "PT011", # pytest-raises-too-broad
    "D102", # undocumented-public-method
]
"**/conftest.py" = [
    "INP001", # implicit-namespace-package
]

[lint.isort]
combine-as-imports = true

[lint.flake8-import-conventions.extend-aliases]
"pyspark.sql.functions" = "fn"

[lint.flake8-annotations]
suppress-dummy-args = true

[lint.flake8-quotes]
inline-quotes = "single"

[lint.flake8-self]
extend-ignore-names = ["_jvm"]

[lint.mccabe]
max-complexity = 15

[lint.pydocstyle]
convention = "google"

[lint.pylint]
max-args = 5
max-bool-expr = 5
max-branches = 12
max-locals = 15
max-nested-blocks = 3
max-positional-args = 5
max-public-methods = 20
max-returns = 6
max-statements = 50

[lint.pyupgrade]
keep-runtime-typing = true

[format]
docstring-code-format = true
indent-style = "space"
line-ending = "lf"
quote-style = "single"
